site_name: Bots EDI Translator Documentation
docs_dir: docs
theme: readthedocs
#extra_css:
#    - css/extra.css
extra_javascript: 
    - js/extra.js
pages:
    - Home: 'index.md'
    - Get started with bots: 
        - Introduction: 'StartIntroduction.md'
        - Installation:
            - Installation: StartInstallProcedure.md
            - Installation Windows: StartInstallWindows.md
            - Installation Linux: StartInstalllinux.md
            - Installation FAQ: StartInstallFaq.md
            - Dependencies: StartInstallDependencies.md
        - Get bots running: StartGetBotsRunning.md
        - Tutorial: 
            - Introduction: StartMyFirstPlugin.md
            - View results: StartMyFirstPluginResults.md
            - Walk through setup: StartMyFirstPluginSetup.md
            - What happened: StartMyFirstPluginDepth.md
    -   Guide for bots-monitor: 
        - Introduction: MonitorIntroduction.md
        - How to rereceive: MonitorRereceive.md
#        - Customize menu: MonitorCustomize.md
    -   Configuration: 
        - Overview: OverviewConfiguration.md
        - How to do configuration: ConfigurationHow.md
        - DIY step by step: ConfigurationDIY.md
    -   Route:
        - Introduction: RoutesIntroduction.md
        - Composite routes: RoutesComposite.md
        - 'PassThrough (no translation)': RoutesPass.md
        -  Route scripting:
            - Introduction: RoutesScripts.md
            - Overview Exit points: RouteScriptsOverviewExits.md
            - Preprocessing recipes: RouteScriptsExample.md
            - Take over whole route: RouteScriptsExampleWholeRoute.md
    -   'Channel/communication':
        - Introduction: ChannelsIntroduction.md
        - Filenames: Filenames.md
        - Database communication: ChannelsDatabase.md
        - Channel scripting: 
            - Introduction: ChannelsScripting.md
            - Small user script: CommunicationScriptsExample.md
            - Subclassing: CommunicationScriptsSubclass.md
            - "communication type 'communicationscript'": CommunicationScriptsType.md
        -   Channel port numbers: ChannelPortNumbers.md
        -   Safe file writing/locking: ChannelFileLock.md
    -   Translation:
        - Introduction: TranslationIntroduction.md
        - How translations work: TranslationDetail.md
        - 'What translation when?': TranslationRules.md
        - Partner specific translations: TranslationperPartner.md
        - Organize partner specific translations: TranslationperPartnerExtended.md
        - 'Chained translations (alt)': TranslationAlt.md
        -  Multiple versions: TranslationVersions.md
    -   Mapping Scripts:
        - Introduction: MappingIntroduction.md
        - How mapping works: MappingHowMappingWorks.md
        - Get from message: MappingGet.md
        - Put in message: MappingPut.md
        - Div mapping functions: MappingFunction.md
        - Code conversion: MappingCcode.md
        - Partner look-up: MappingPartnerLookup.md
        - Calculate and count: MappingCalculate.md
        - 'Persist (store data)': MappingPersist.md
        - 'EAN/UCC check digits': MappingEAN.md
        - Change and delete: MappingChangedelete.md
#        - Access to envelope: MappingEnvAccess.md
    -   Grammars:
        - Introduction: GrammarsIntroduction.md
        - How to get grammars: GrammarsHowToGet.md
        - Syntax parameters: GrammarsSyntax.md
        - Structure: GrammarsStructure.md
        - Recorddefs: GrammarsRecorddefs.md
        - Nextmessage: GrammarsNextmessage.md
        - Nextmessageblock: GrammarsNextmessageblock.md
        - Partner dependent syntax: GrammarsPartnerSyntax.md
        - Edifact charsets: ConfigurationCharset.md
        - XML namespaces: XMLnamespace.md
    -   'Document View (botskey)': ConfigurationBotskey.md
    -   'User Scripting':
        - Introduction: UserScriptingIntroduction.md
        - Bots engine scripting: RouteScriptsExampleBotsEngine.md
    -   'Confirmations/acknowledgements': Confirmations.md
    -   'Split/merge/envelope':
        - Introduction: ConfigurationSplitMerge.md
        - Split edi files: ConfigurationSplit.md
        - 'Merge/envelope edi files': ConfigurationMerge.md
        - 'Envelope scripting': EnvelopeScripting.md
    -   Edi partners: 
        - Introduction: ConfigurationPartners.md
        - Partner specific translations: TranslationperPartner.md
        - Organize partner specific translations: TranslationperPartnerExtended.md
        - Partner dependent syntax: GrammarsPartnerSyntax.md
        - Partner groups: ConfigurationPartnerGroup.md
        - Email addresses: ChannelsRecipes.md
        - Partner look-up: MappingPartnerLookup.md
        - Envelope scripting: EnvelopeScripting.md
    -   'Character-sets/unicode': Charsets.md
    -   How to debug: Debug.md
    -   Plugins:
        - Introduction: PluginIntroduction.md
        - Install a plugin: PluginInstall.md
        - Plugins at sourceforge: PluginList.md
        - Make a plugin: PluginGenerate.md
        - Plugin details: PluginDetail.md
    -   Deployment and usage:
        - Introduction: DeploymentIntroduction.md
        - Running bots-engine: DeploymentEngineOverview.md
        - Schedule bots-engine: DeploymentEngine.md
        - Job Queue: Jobqueue.md
        - Directory Monitor: DirMonitor.md
        - Return codes: DeploymentEngineReturnCode.md
    -   Handle production errors: DeploymentHandleErrors.md
    -   Email notification for errors: DeploymentErrorReports.md
    -   Archiving of EDI files: Archiving.md
    -   'Run as service/daemon': DaemonProcesses.md
    -   Linux Daemons: LinuxDaemons.md
    -   Windows Services: WindowsServices.md
    -   Multiple environments:
        - Introduction: DeploymentMultipleEnvironments.md
        - Virtual environments: DeploymentMultipleEnvironmentsVirtual.md
#    -   Maintenance: DeploymentMaintenance.md
    -   Advanced Deployment: DeploymentAdvanced.md
    -   User Rights: UserSecurity.md
    -   Bots-monitor over HTTPS: DeploymentHttps.md
    -   Use Apache2: DeploymentApache2.md
    -   'Use MySQL/PostgreSQL': DeploymentOtherDatabase.md
    -   Using AS2 with Bots: DeploymentAS2.md
    -   Configuration change management: DeploymentEnv.md
    -   Isolated acceptance test: DeploymentAcceptance.md
    -   'Push test->production': DeploymentAutopush.md
    -   'Build test-set': DeploymentTestSet.md
    -   'Performance/big volumes': Performance.md
    -   'Troubleshooting FAQ': Troubleshooting.md
    -   'Overview':
        -   Introduction: OverviewIntroduction.md
        -   'The name "Bots"': BotsName.md
#        -   'Features of bots': 'http://bots.sourceforge.net/en/about_features.shtml'
        -   Technical overview: OverviewDetail.md
        -   Directories and files: OverviewDirectoryLayout.md
        -   Configuration files: StartConfigurationFiles.md
        -   Glossary of terms: Glossary.md
    -   Changes and migrate:
        - Introduction: Migrate.md
        - Bots 3.2.0: Migrate320.md
        - Changes: V320changes.md
        - Bots 3.1.0: Migrate310.md
        - Changes: V310changes.md
        - Migrate: V310migrate.md
        - Bots 3.0.0: Migrate300.md
        - Changes: V300changes.md
        - Migrate: V300migrate.md
        - 'Changes 3.0.0rc/3.0.0': V300rcchanges.md
        - 'Changes/migrate 2.2.0': Migrate220.md
        - 'Changes/migrate 2.1.0': Migrate210.md
        - 'Migrate Kid to Genshi': MigrateKidGenshi.md
        - 'Migrate Django versions': MigrateDjango.md
        - 'Migrate database': MigrateDatabase.md
    -   Tutorials: 
        - Introduction: TutorialHome.md
        - EDI Basics: TutorialEdiBasics.md
        - High Level Business Flow: TutorialHighLevelBusinessFlow.md
        - Advance Shipment Notice: TutorialAdvanceShipNotice.md
    -   'Integration with Odoo/OpenERP': OdooIntegration.md
    -   'New to python?': NewToPython.md
    -   'External reference links': Links.md
    -   Useful Tools: UsefulTools.md



